###
GET http://localhost:7000/contents

###
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "bbb@mail.com",
  "firstName": "TestFN",
  "lastName": "TestFN",
  "password": "password123"
}
###
POST http://localhost:7000/auth
Content-Type: application/json

{
  "password": "password123",
  "email": "test@mail.com"
}

### POST Subscriber email
POST http://localhost:7000/subscribers
Content-Type: application/json

{
  "email": "subscribertest2@mail.com"
}
### POST No Subscriber email
POST http://localhost:7000/subscribers
Content-Type: application/json

{
  "email": ""
}
### GET Subscribers List
GET http://localhost:7000/subscribers

### DELETE Subscriber
DELETE http://localhost:7000/subscribers/5a56db71cba7f15514f63758