###
GET http://localhost:7000/contents

### Read one video
GET http://localhost:7000/contents/5a600a0e2f18f3294ad71470

###
POST http://localhost:7000/auth/register
Content-Type: application/json

{
  "email": "bbb0@mail.com",
  "firstName": "TestFN",
  "lastName": "TestFN",
  "password": "password123"
}
### Sign in
POST http://localhost:7000/auth
Content-Type: application/json

{
  "password": "password123",
  "email": "bbb@mail.com"
}
### Create Content
POST http://localhost:7000/contents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiYkBtYWlsLmNvbSIsImlhdCI6MTUxNjA3NDkyMSwiZXhwIjoxNTE2Njc5NzIxLCJzdWIiOiI1YTVkNTgyMjEyNjc2NjYzY2EzYmE5ZTQifQ.fsCDA07F3cyiqmUT79VJeuPXW_Rz3eEo5VjLELV9EO0
Content-Type: application/json

{
  "title": "testTitle",
  "subtitle": "testSubtitle",
  "youtubeURL": "pornhub.com",
  "description": "navy top secret questions" 
}

### Update Content

PUT http://localhost:7000/contents/5a56c08bd6cece1368823525
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpYXQiOjE1MTU2MzQ1NjIsImV4cCI6MTUxNjIzOTM2Miwic3ViIjoiNWE1NTlmOTI4NTg3MGUwN2I0MjhmZTVmIn0.EendFFhK794DxlSObZbbZVSeZh9x9QTEPWhej6BVH14
Content-Type: application/json

{
  "youtubeURL": "clayton knows"
}

### Delete Content
DELETE http://localhost:7000/contents/5a56c08bd6cece1368823525
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpYXQiOjE1MTU2MzQ1NjIsImV4cCI6MTUxNjIzOTM2Miwic3ViIjoiNWE1NTlmOTI4NTg3MGUwN2I0MjhmZTVmIn0.EendFFhK794DxlSObZbbZVSeZh9x9QTEPWhej6BVH14

### Create Subscriber
POST http://localhost:7000/subscribers
Content-Type: application/json

{
  "email": "subscriber@test.com"
}

POST http://localhost:7000/subscribers
Content-Type: application/json

{
  "email": "test1@gmail.com" 
}
