@host = https://jitsmob-api-dwbvwvaflb.now.sh

###
GET {{host}}/contents

### add admin
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "ccc@mail.com",
  "firstName": "TestFN",
  "lastName": "TestFN",
  "password": "password123"
}
### Sign in
POST {{host}}/auth
Content-Type: application/json

{
  "password": "password123",
  "email": "ccc@mail.com"
}
### Create Content
POST {{host}}/contents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFhYUBtYWlsLmNvbSIsImlhdCI6MTUxNjY3MDY4OSwiZXhwIjoxNTE3Mjc1NDg5LCJzdWIiOiI1YTY2OGVlMGViMzViYTAwOWNlNTdlNTcifQ.0u1f5D3xmJHO4ODwWrZn1vSqGfQrTyMrunPVirskwLQ
Content-Type: application/json

{
  "title": "HIPS - Part 3B - HAMSTRINGS (BJJ/MMA INJURY PREVENTION)",
  "category": "Strength",  
  "bodyPart": "Legs",
  "youtubeURL": "https://www.youtube.com/watch?v=tAt-A8d4AM4",
  "description": "Here is part 3B of this new series aimed at keeping you injury free, more mobile, more flexible and all round moving better."
}

### Update Content

PUT {{host}}/contents/5a5809d737696f009f7e741f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiYkBtYWlsLmNvbSIsImlhdCI6MTUxNTcxOTA2NiwiZXhwIjoxNTE2MzIzODY2LCJzdWIiOiI1YTU4MDk4YTM3Njk2ZjAwOWY3ZTc0MWQifQ.R4TQb9Tw6IItL5Gaxc-xdurzc6aJ8Q3TmzjxU4y68cU
Content-Type: application/json

{
  "youtubeURL": "clayton knows"
}

### Delete Content
DELETE {{host}}/contents/5a6556f2c275d1006b4c083d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiYkBtYWlsLmNvbSIsImlhdCI6MTUxNjU5MjI0NCwiZXhwIjoxNTE3MTk3MDQ0LCJzdWIiOiI1YTU4MDk4YTM3Njk2ZjAwOWY3ZTc0MWQifQ.9_65yTabAVAFCAguv2MTEBG38ypEe2qYAV8_xqSsLSc


### Create New User

POST {{host}}/authUser/register
Content-Type: application/json

{
  "email": "daniel@abc.com",
  "firstName": "TestUserFN",
  "lastName": "TestUserLN",
  "password": "aaaaaa"
}

### Sign in User
POST {{host}}/auth
Content-Type: application/json

{
  "email": "daniel@abc.com"
  "password": "aaaaaa",
}

### Read users' workout
GET {{host}}/userworkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0QHRlc3R1c2VyLmNvbSIsImlhdCI6MTUxNjY2OTY3MiwiZXhwIjoxNTE3Mjc0NDcyLCJzdWIiOiI1YTY2OGFlNzhjZjg4NDQ1YTA5MzcxMDgifQ.d2ZnauNZgnf_R4ZX94iYoTKj81Cr1LoQovC9TkN0B34

### Add to userworkout
POST {{host}}/userworkout/contents/5a6687b4ba9ac1487c2bf163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0QHRlc3R1c2VyLmNvbSIsImlhdCI6MTUxNjY2OTY3MiwiZXhwIjoxNTE3Mjc0NDcyLCJzdWIiOiI1YTY2OGFlNzhjZjg4NDQ1YTA5MzcxMDgifQ.d2ZnauNZgnf_R4ZX94iYoTKj81Cr1LoQovC9TkN0B34

### Remove from userworkout
DELETE {{host}}/userworkout/contents/5a6687b4ba9ac1487c2bf163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0QHRlc3R1c2VyLmNvbSIsImlhdCI6MTUxNjY2OTY3MiwiZXhwIjoxNTE3Mjc0NDcyLCJzdWIiOiI1YTY2OGFlNzhjZjg4NDQ1YTA5MzcxMDgifQ.d2ZnauNZgnf_R4ZX94iYoTKj81Cr1LoQovC9TkN0B34



