@host = https://jitsmob-api-ffzpnqjwrw.now.sh

###
GET {{host}}/contents

### add admin
POST {{host}}/auth/register
Content-Type: application/json

{
  "email": "daniel@abc.com",
  "firstName": "TestFN",
  "lastName": "TestFN",
  "password": "aaaaaa"
}
### Sign in
POST {{host}}/auth
Content-Type: application/json

{
  "password": "password123",
  "email": "ccc@mail.com"
}
### Create Content
POST {{host}}/contents
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNjY0BtYWlsLmNvbSIsImlhdCI6MTUxNjc5OTM4MSwiZXhwIjoxNTE3NDA0MTgxLCJzdWIiOiI1YTY2OGY5YWViMzViYTAwOWNlNTdlNWIifQ.taNTWJuaZ9oa8KeiDj5GD9YnXlxh9Cw3hHwty8vjpbw
Content-Type: application/json

{
    "title": "BJJ / MMA INJURY PREVENTION SERIES",
    "category": "Strength",
    "bodyPart": "Spine",
    "youtubeURL": "https://www.youtube.com/watch?v=oSzW_Dv3kS8",
    "description": "ALL ABOUT INJURY PREVENTION, BODY MAINTENANCE, MOBILITY & FLEXIBILITY SPECIFICALLY FOR BRAZILIAN JIU-JITSU & MMA. "
  }

### Update Content

PUT {{host}}/contents/5a5809d737696f009f7e741f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiYkBtYWlsLmNvbSIsImlhdCI6MTUxNTcxOTA2NiwiZXhwIjoxNTE2MzIzODY2LCJzdWIiOiI1YTU4MDk4YTM3Njk2ZjAwOWY3ZTc0MWQifQ.R4TQb9Tw6IItL5Gaxc-xdurzc6aJ8Q3TmzjxU4y68cU
Content-Type: application/json

{
  "youtubeURL": "clayton knows"
}

### Delete Content
DELETE {{host}}/contents/5a668efdeb35ba009ce57e58
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNjY0BtYWlsLmNvbSIsImlhdCI6MTUxNjc5OTM4MSwiZXhwIjoxNTE3NDA0MTgxLCJzdWIiOiI1YTY2OGY5YWViMzViYTAwOWNlNTdlNWIifQ.taNTWJuaZ9oa8KeiDj5GD9YnXlxh9Cw3hHwty8vjpbw


### Create New User

POST {{host}}/authUser/register
Content-Type: application/json

{
  "email": "daniel@abc.com",
  "firstName": "TestUserFN",
  "lastName": "TestUserLN",
  "password": "aaaaaa"
}

### Sign in User
POST {{host}}/auth
Content-Type: application/json

{
  "email": "daniel@abc.com"
  "password": "aaaaaa",
}

### Read users' workout
GET {{host}}/userworkout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0QHRlc3R1c2VyLmNvbSIsImlhdCI6MTUxNjY2OTY3MiwiZXhwIjoxNTE3Mjc0NDcyLCJzdWIiOiI1YTY2OGFlNzhjZjg4NDQ1YTA5MzcxMDgifQ.d2ZnauNZgnf_R4ZX94iYoTKj81Cr1LoQovC9TkN0B34

### Add to userworkout
POST {{host}}/userworkout/contents/5a6687b4ba9ac1487c2bf163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0QHRlc3R1c2VyLmNvbSIsImlhdCI6MTUxNjY2OTY3MiwiZXhwIjoxNTE3Mjc0NDcyLCJzdWIiOiI1YTY2OGFlNzhjZjg4NDQ1YTA5MzcxMDgifQ.d2ZnauNZgnf_R4ZX94iYoTKj81Cr1LoQovC9TkN0B34

### Remove from userworkout
DELETE {{host}}/userworkout/contents/5a6687b4ba9ac1487c2bf163
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZpcnN0QHRlc3R1c2VyLmNvbSIsImlhdCI6MTUxNjY2OTY3MiwiZXhwIjoxNTE3Mjc0NDcyLCJzdWIiOiI1YTY2OGFlNzhjZjg4NDQ1YTA5MzcxMDgifQ.d2ZnauNZgnf_R4ZX94iYoTKj81Cr1LoQovC9TkN0B34



